### ISSUE TITLE
about compiler

### ISSUE THREAD

**Issue by costlife** [fis-scaffold/rosetta#1]
When I created an element with code '&nbsp; ','&copy;' ,etc,
fis3 didn't correctly recognise my code.

```
<div class="footer">
            &copy;2015 Baidu <a href="http://www.baidu.com/duty/" target="_blank">使用百度前必读</a>&nbsp;|&nbsp; <span>京ICP证030173号</span>
</div>
```

It only exported 

```
<span>京ICP证030173号</span>
```

**Comment by 2betop** [comment]
It seems the `Rosetta.create` ignored the text content. 

@jiexuangao  please check this out.

**Comment by gloriagxx** [comment]
fixed~

**Comment by oxUnd** [comment]
...
